# add your desired knowledge graph components here

protein:
  represented_as: node
  preferred_id: uniprot
  input_label: Protein
  properties:
    species: str

macromolecular complex:
  represented_as: node
  input_label: MacromolecularComplex
  properties:
    species: str

ligand receptor interaction:
  represented_as: edge
  input_label: LigandReceptorInteraction
  is_a: pairwise molecular interaction
  properties:
    species: str
